title: Portafolio Maria Saavedra
description: Bienvenidos al repositorio de la asignatura de cuarto de Comunicación Proyectos para la Web donde incluiremos los productos mediáticos que creemos en el resto de asignaturas de este curso

url: http://mariasaav.github.io
baseurl: ""

author:
  name: Maria Saavedra
  picture: 
  email: maria.saavedra@opendeusto.es
  links:
    - title: GitHub
      url: https://github.com/mariasaav
      icon: fab fa-github-square

remote_theme: mmistakes/minimal-mistakes@4.17.0

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
